os: linux
dist: trusty

language: node_js
node_js:
 - lts/*

addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

branches:
 only:
  - master
  - api

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm ci

script:
 - bash tasks.build.sh
 - bash api.deploy.sh

deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com
