language: node_js
node_js:
 - lts/*

branches:
 only:
  - master

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

install:
  - npm ci

script:
 - npm run build

deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com
